default_queue_type = quorum
consumer_timeout = 1800000
channel_max = 1024
heartbeat = 30
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB
log.console = true
log.console.level = info
