bind 0.0.0.0
protected-mode yes
port 6379
appendonly no
save ""
maxmemory 256mb
maxmemory-policy allkeys-lru
timeout 0
tcp-keepalive 60
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""

