apiVersion: 1
datasources:
  - name: FraudCell Prometheus
    uid: fraudcell-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

